" Generated by vim-plug
" Mon Aug 24 10:19:31 2026
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ale'].commit = 'e1789bc54483d76ac9ddb40b633d1645c8281914'
silent! let g:plugs['auto-pairs'].commit = '39f06b873a8449af8ff6a3eee716d3da14d63a76'
silent! let g:plugs['catppuccin'].commit = '78c40a773e56d05e1c4e29216c45a483bdd67351'
silent! let g:plugs['coc.nvim'].commit = '95073dab304d4c35fd468c0eb57f4bfe25bf8eda'
silent! let g:plugs['fzf'].commit = 'd46bfd005a8bb55b6e440da98470c23906982437'
silent! let g:plugs['fzf.vim'].commit = 'd2a59a992a2455f609c0fde2ebd84427ea8f919a'
silent! let g:plugs['lightline.vim'].commit = 'd042c506cb2e7a59112a72447e0b5fe8739d9d1d'
silent! let g:plugs['nerdtree'].commit = '690d061b591525890f1471c6675bcb5bdc8cdff9'
silent! let g:plugs['ultisnips'].commit = '62aca2a735b76d24a8fc7862f902330ac688849b'
silent! let g:plugs['vim-commentary'].commit = '64a654ef4a20db1727938338310209b6a63f60c9'
silent! let g:plugs['vim-fugitive'].commit = '3b753cf8c6a4dcde6edee8827d464ba9b8c4a6f0'
silent! let g:plugs['vim-gitgutter'].commit = '90b75207bd9b55d8ac4af15f72b4e935462014d0'
silent! let g:plugs['vim-highlightedyank'].commit = '285a61425e79742997bbde76a91be6189bc988fb'
silent! let g:plugs['vim-kitty'].commit = 'cd72f2d9cfee8d6aba5a180a5ac3ca265b5d3a46'
silent! let g:plugs['vim-obsession'].commit = 'ed9dfc7c2cc917ace8b24f4f9f80a91e05614b63'
silent! let g:plugs['vim-polyglot'].commit = 'f061eddb7cdcc614c8406847b2bfb53099832a4e'
silent! let g:plugs['vim-repeat'].commit = '65846025c15494983dafe5e3b46c8f88ab2e9635'
silent! let g:plugs['vim-rhubarb'].commit = '5496d7c94581c4c9ad7430357449bb57fc59f501'
silent! let g:plugs['vim-snippets'].commit = 'ededcf7581962ee616cadab360d5966f3307f11a'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vim-test'].commit = '2676d84c6901e484df00b5d728bd6a345d47ee12'
silent! let g:plugs['vim-tmux-navigator'].commit = 'e41c431a0c7b7388ae7ba341f01a0d217eb3a432'
silent! let g:plugs['vim-yoink'].commit = '89ed6934679fdbc3c20f552b50b1f869f624cd22'
silent! let g:plugs['vimspector'].commit = '34099d18d8957bb3db5f396c8ca993ffb246a437'

PlugUpdate!
